### ISSUE TITLE
Integration with idf.py

### ISSUE THREAD

**Issue by PilotAware** [jimparis/esptool-ftdi#3]
@jimparis 
Hi Jim, I think this may be a solution I have been looking for !
I am pretty hands off with the low level detail of the build infrastructure, and the setup I have is all based around the usage of idf.py
Do you know how I would integrate with that flow ?

Thx
Lee

**Comment by jimparis** [comment]
One way would be to modify `idf.py` to add `esptool-ftdi.py` before the `esptool.py` commandline.  Maybe something like this patch against the esp-idf repository:
```patch
diff --git a/tools/idf_py_actions/serial_ext.py b/tools/idf_py_actions/serial_ext.py
index f947f2a5ef23..32df583c63d3 100644
--- a/tools/idf_py_actions/serial_ext.py
+++ b/tools/idf_py_actions/serial_ext.py
@@ -34,7 +34,7 @@ def action_extensions(base_actions, project_path):
         esptool_path = os.path.join(os.environ["IDF_PATH"], "components/esptool_py/esptool/esptool.py")
         if args.port is None:
             args.port = _get_default_serial_port()
-        result = [PYTHON, esptool_path]
+        result = [PYTHON, "/path/to/esptool-ftdi/esptool-ftdi.py", esptool_path]
         result += ["-p", args.port]
         result += ["-b", str(args.baud)]
```
Another alternative would be to rename the original `esptool.py` and to put this `esptool-ftdi.py` script in its place, with a hardcoded path to the original script (instead of passing it on the command line).

**Comment by PilotAware** [comment]
Hi Jim
Many thanks for getting back to me
Unfortunately in the end I could not rid myself of python errors I must have some library incompatibilities.
I generally work under Linux, in this case I simply shared the build folder with my Windows machine and use that to flash my device. Annoying, but it works

Thanks for your help, I may try to get back to this at some point
Thx
Lee

**Comment by tobiasgraf** [comment]
Hi,

this helped me solve my usecase.

In case someone reads this, here is what i did.

I'm using aws freertos, which comes with esp-idf (v3.3) bundeled, and to flash my esp32 I use a command like this
`amazon-freertos/vendors/espressif/esp-idf/tools/idf.py  flash -p /dev/ttyUSB0 build` 
To get it to work, I copied the `esptool-ftdi.py` next to the normal `esptool.py` (`amazon-freertos/vendors/espressif/esp-idf/components/esptool_py/esptool`).

I then applied your suggested changes (some adjustments)

```patch
diff --git a/amazon-freertos/vendors/espressif/esp-idf/tools/idf.py b/amazon-freertos/vendors/espressif/esp-idf/tools/idf.py
index 8380513..7fd83c0 100755
--- a/amazon-freertos/vendors/espressif/esp-idf/tools/idf.py
+++ b/amazon-freertos/vendors/espressif/esp-idf/tools/idf.py
@@ -276,9 +276,10 @@ def build_target(target_name, args):
 
 def _get_esptool_args(args):
     esptool_path = os.path.join(os.environ["IDF_PATH"], "components/esptool_py/esptool/esptool.py")
+    esptool_ftdi_path = os.path.join(os.environ["IDF_PATH"], "components/esptool_py/esptool/esptool-ftdi.py")
     if args.port is None:
         args.port = get_default_serial_port()
-    result = [PYTHON, esptool_path]
+    result = [PYTHON, esptool_ftdi_path, esptool_path]
     result += ["-p", args.port]
     result += ["-b", str(args.baud)]
 
```

To get it to work I also needed to install 
` sudo pip install pyusb`

and [compile and install libftdi1.4 ](https://github.com/adafruit/Adafruit_Python_GPIO/issues/87#issuecomment-460772378) but also with `-DBUILD_TESTS:BOOL=OFF` added to cmake command.

Thanks for your work :+1:

**Comment by jimparis** [comment]
Support was added upstream.  See https://github.com/jimparis/esptool-ftdi/#integrating-with-esp-idf
