### ISSUE TITLE
Stopped working with esptool 4.0

### ISSUE THREAD

**Issue by M-Bab** [jimparis/esptool-ftdi#9]
Esptool 4.0 was released and after the update the esptool-ftdi stopped working. I tried some workarounds like being the open pool requests or importing esptool instead of running it as an external tool.

I think I advanced a couple of steps but the esp32 is still not correctly reset to bootloader mode. Any chance you have a look at it? Otherwise I will take a look but it might need some time till I get to it.

**Comment by cms-pm** [comment]
What version of esptool.py was known to work?

**Comment by M-Bab** [comment]
As far as I tried, it worked with esptool versions 3.x

**Comment by jimparis** [comment]
Fixed in 7d0766ef6e559c55621e3161a34ed1ea975a215b, thank you for reporting
